# Generated by Django 2.2.2 on 2019-06-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField()),
                ('department_leader', models.TextField()),
                ('account', models.TextField()),
                ('cost_centre', models.TextField()),
                ('project', models.TextField(blank=True, null=True)),
                ('refund_type', models.TextField(choices=[('cash', 'Bargeld'), ('bank_account', 'Überweisung'), ('amazon', 'Amazon-Account'), ('credit_card', 'Kreditkarte')])),
                ('bank_account_owner', models.TextField(blank=True, null=True)),
                ('bank_account_iban', models.TextField(blank=True, null=True)),
                ('bank_account_bic', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=8)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refund.Refund')),
            ],
        ),
    ]
