# Generated by Django 2.2.2 on 2019-06-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='sum',
            new_name='amount',
        ),
    ]
