# Generated by Django 2.2.2 on 2019-06-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0002_auto_20190606_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='account',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='refund',
            name='bank_account_bic',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='bank_account_iban',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='bank_account_owner',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='cost_centre',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='refund',
            name='department_leader',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='refund',
            name='project',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
