# Generated by Django 2.2.2 on 2019-06-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0003_auto_20190608_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='receipt_0_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_0_picture',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_1_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_1_picture',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_2_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_2_picture',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_3_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_3_picture',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_4_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_4_picture',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_5_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_5_picture',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_6_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_6_picture',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_7_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_7_picture',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_8_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_8_picture',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_9_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refund',
            name='receipt_9_picture',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
