# Generated by Django 2.2.2 on 2019-06-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0004_auto_20190608_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='receipt_0_picture',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_1_picture',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_2_picture',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_3_picture',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_4_picture',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_5_picture',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_6_picture',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_7_picture',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_8_picture',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_9_picture',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
