# Generated by Django 2.2.2 on 2019-06-24 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refund', '0005_auto_20190608_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refund',
            name='account',
            field=models.CharField(max_length=128, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='bank_account_bic',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Bank Account BIC'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='bank_account_iban',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Bank Account IBAN'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='bank_account_owner',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Bank Account Owner'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='cost_centre',
            field=models.CharField(max_length=128, verbose_name='Cost Centre'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='date_submitted',
            field=models.DateField(verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='department_leader',
            field=models.CharField(max_length=128, verbose_name='Department Leader'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='project',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_0_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_1_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_2_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_3_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_4_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_5_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_5_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_6_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_6_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_7_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_7_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_8_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_8_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_9_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_9_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.TextField(choices=[('cash', 'Bargeld'), ('bank_account', 'Überweisung'), ('amazon', 'Amazon-Account'), ('credit_card', 'Kreditkarte')], verbose_name='Refund Type'),
        ),
    ]
