# Generated by Django 2.2.2 on 2019-06-24 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0006_auto_20190624_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
