# Generated by Django 2.2.2 on 2019-07-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0007_auto_20190624_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='receipt_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Sum'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_0_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Sum'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_1_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Sum'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_2_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Sum'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_3_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Sum'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_4_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_5_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Sum'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_5_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_6_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Sum'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_6_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_7_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Sum'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_7_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_8_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Sum'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_8_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_9_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Sum'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='receipt_9_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Receipt'),
        ),
    ]
