# Generated by Django 2.2.2 on 2019-07-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0008_auto_20190701_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='account',
        ),
    ]
