# Generated by Django 2.2.2 on 2019-07-14 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0011_auto_20190714_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='cost_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centre', to='refund.CostCentre', verbose_name='Cost Centre'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='department_leader',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_leader', to=settings.AUTH_USER_MODEL, verbose_name='Department Leader'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='refund.Project', verbose_name='Project'),
        ),
    ]
