# Generated by Django 2.2.2 on 2019-10-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0012_auto_20190714_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='approved',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
